---
- stat:
    path: /var/www/xhprof
  register: check_xhprof

- name: Creates tmp directory
  file:
    path: /tmp/xhprof
    state: directory
    recurse: yes

- name: Creates www directory
  file:
    path: /var/www/xhprof
    state: directory
    recurse: yes

- name: Clone xhprof repo
  git:
    repo: https://github.com/longxinH/xhprof
    dest: /var/www/xhprof
    version: master

- name: Install
  shell: cd /var/www/xhprof/extension && phpize && ./configure && make && make install
  when: check_xhprof.stat.exists == False

- name: Copy php fpm config
  copy: src=xhprof.ini dest=/etc/php/{{ php_version }}/fpm/conf.d/030-xhprof.ini
  when: check_xhprof.stat.exists == False
  notify:
      - restart php-fpm
