---
- name: Install python-software-properties
  apt:
    name:
      - python-software-properties
      - software-properties-common
    state: present
    autoclean: yes

- name: Install required php packages
  apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-mysql
      - php{{ php_version }}-intl
      - php{{ php_version }}-curl
      - php{{ php_version }}-fpm
      - php{{ php_version }}-cli
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-dom
      - php{{ php_version }}-gmp
      - php{{ php_version }}-apcu
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-zip
      - php{{ php_version }}-dev
      - php{{ php_version }}-gd
      - php-memcached
      - php-imagick
#      - php-xdebug
      - php-pear
      - php-yaml
      - percona-toolkit
      - pkg-config
      - memcached
      - libmcrypt-dev
    state: present
    autoclean: yes

- name: Check pecl mcrypt installed
  command: pecl list | grep mcrypt
  register: pecl_mcrypt

- name: Install pecl mcrypt
  shell: pecl install mcrypt-1.0.1
  when: pecl_mcrypt  == ""

- name: Copy php fpm config
  copy: src=custom.ini dest=/etc/php/{{ php_version }}/fpm/conf.d/030-custom.ini

- name: Copy php cli config
  copy: src=custom.ini dest=/etc/php/{{ php_version }}/cli/conf.d/030-custom.ini

- name: Copy fpm config
  copy: src=www.conf dest=/etc/php/{{ php_version }}/fpm/pool.d/www.conf

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

- name: Configure composer cache directory to avoid using slow NFS
  shell: composer config --global cache-dir /dev/shm/composer/cache

- name: Update pecl
  shell: pecl channel-update pecl.php.net

- name: Check pecl apcu installed
  command: pecl list | grep apcu
  register: pecl_apcu

- name: Install pecl apcu
  shell: pecl install apcu;
  when: pecl_apcu  == ""

- name: Check pecl imagick installed
  command: pecl list | grep imagick
  register: pecl_imagick

- name: Install pecl imagick
  shell: pecl install imagick;
  when: pecl_imagick  == ""

- name: Set correct owner
  file: path=/var/www owner=vagrant group=vagrant state=directory
  notify:
    - restart php-fpm
