---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy location
  copy: src=locations.conf dest=/etc/nginx/locations.conf

- name: Copy mime
  copy: src=mime.types dest=/etc/nginx/mime.types

- name: Copy vhosts
  copy: src=sites-enabled dest=/etc/nginx/

- name: Copy across new nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx