- name: Add apt repository for PHP
  become: yes
  apt_repository: repo='ppa:ondrej/php'

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install required base packages
  apt:
    name:
      - curl
      - git
      - wget
      - nano
      - vim
      - zip
      - unzip
#      - multitail
      - cachefilesd
    state: present
    autoclean: yes

- name: Copy .bashrc file
  copy: src=bashrc dest=/home/vagrant/.bashrc

- name: Enable cachefilesd
  shell: echo 'RUN=yes' > /etc/default/cachefilesd

- name: Fix curl
  apt: name=libcurl4-gnutls-dev state=present
