- name: Add apt repository for PHP
  become: yes
  apt_repository: repo='ppa:ondrej/php'

- name: Update apt packages
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Install required base packages
  apt:
    name:
      - curl
      - git
      - wget
      - nano
      - vim
      - python-mysqldb
      - zip
      - unzip
      - cachefilesd
    state: present
    autoclean: yes

- name: Copy .bashrc file
  copy: src=bashrc dest=/home/vagrant/.bashrc

- name: Enable cachefilesd
  shell: echo 'RUN=yes' > /etc/default/cachefilesd

- name: Fix curl
  apt: name=libcurl4-gnutls-dev state=present