---
- hosts: all
  become: true
  vars:
    document_root: /vagrant
    www_user: vagrant
    www_group: vagrant
  roles:
    - base
    - nginx
    - mysql
    - php
    - xhprof
    - node
    - clean